checks:
  php: true

tools:
  php_sim: true
  php_pdepend: true
  php_analyzer: true
  php_cs_fixer: true

build:
  dependencies:
    before:
      - composer dump-autoload -o
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
        coverage:
          file: 'clover.xml'
          format: 'php-clover'
